# global variables including data and page nums

# data
DESCR_STRAT = []
# other data entries

# page nums
FAILURE = -2
QUIT = -1
MAIN_MENU = 0
FACTION_PLAYABILITY = 1
CURRENT_FACTION_PLAYABILITY = 2
PLAYABLE_TO_UNLOCKABLE = 3
PLAYABLE_TO_NONPLAYABLE = 4
UNLOCKABLE_TO_PLAYABLE = 5
UNLOCKABLE_TO_NONPLAYABLE = 6
NONPLAYABLE_TO_PLAYABLE = 7
NONPLAYABLE_TO_UNLOCKABLE = 8

PAGES = []
